### PR TITLE
Added city operations  functionality to get cities, save city and unsave city

### PR DESCRIPTION
**Pull request by slroberts**
------------------
[Added city operations reducers and actions (get cities, save city and unsave city)](https://trello.com/c/3HmQgOBX)
-------------------------
### Location:
-reducers/index.js
-reducers/cityOperations.js
-actions/index.js
-actions/cityOperations.js 
-HomeContainer.js
-RenderCitySearchResults.js
-CitySearchResultsContainer.js
-MapboxGLMap.js
### Details:
1) User can save favorite city data to user dashboard.
-------------------------
## Committed Features:
1 | Set token to local storage to use when saving city.
2 | Created cityOperations ( fetch, save & unsave ).
3 | Wired up save city action.
4 | Added save button, made responsive.
5 | Passed coordinates as props.

### CODE REVIEW

**Review by AndyWatts712 — APPROVED** [review]
Great, thanks for the Save button and other features.

**Review by AndyWatts712 — APPROVED** [review]
Great, much cleaner now.

**Review by BritneyParkerson — APPROVED** [review]
Looks great

**Review by codyt11 — APPROVED** [review]
well done Shomari, your abilities to work through these problems are superb! your code is clean, as always and i'm glad we got the lat and long features set up!

**Pull request merged**
